version: '3.7'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"